const GET_NAV_INFO = "GET_NAV_INFO"
const GET_HOME_INFO = "GET_HOME_INFO"
const CHANGE_ACTIVE_INDEX = "CHANGE_ACTIVE_INDEX"
const ADD_HOME_SPECIAL = "ADD_HOME_SPECIAL"
const ADD_HOME_SPECIAL1 = "ADD_HOME_SPECIAL1"
const ADD_HOME_DETAIL = "ADD_HOME_DETAIL"
const ADD_HOME_SPECIALS = "ADD_HOME_SPECIALS"
const GET_ALONE_BANNERS = "GET_ALONE_BANNERS"
const GET_HOME_TICKET = "GET_HOME_TICKET"
const GET_HOEM_DETAIL = "GET_HOEM_DETAIL"
const GET_HOME_BANNERDETAIL = "GET_HOME_BANNERDETAIL"
const GET_RECO_BANNER = "GET_RECO_BANNER"
const GET_FIND_BANNERS = "GET_FIND_BANNERS"
const CHANGE_SCROLL_FLAG = "CHANGE_SCROLL_FLAG"

export {
    GET_NAV_INFO,
    GET_HOME_INFO,
    CHANGE_ACTIVE_INDEX,
    ADD_HOME_SPECIAL,
    ADD_HOME_SPECIAL1,
    ADD_HOME_DETAIL,
    ADD_HOME_SPECIALS,
    GET_ALONE_BANNERS,
    GET_HOME_TICKET,
    GET_HOEM_DETAIL,
    GET_HOME_BANNERDETAIL,
    GET_RECO_BANNER,
    GET_FIND_BANNERS,
    CHANGE_SCROLL_FLAG
}